### ISSUE TITLE
Update grails-quartz for Grails 7

### ISSUE THREAD

**Issue by jamesfredley** [grails-plugins/grails-quartz#131]
4.0.x branch has been created for Grails 7: https://github.com/grails/grails-quartz

**Comment by jdaugherty** [comment]
Internally, we use the quartz spring starter and it works perfectly as-is.  What are people's thoughts about publishing a guide for this way instead?

**Comment by jdaugherty** [comment]
FYI: https://github.com/quartz-scheduler/quartz/issues/1134 - quartz was released so it should work with the jakarta packages now

**Comment by amondel2** [comment]
@jamesfredley I made some updates for this plugin for Java 17 (this was mostly done already), Spring 6.2.0,  and Grails 7.0.0-snapshot in my  [branch](https://github.com/amondel2/grails-quartz/tree/grails-7).  Before I do the MR where do we stand on the following.

1. Keep or  remove buildSrc dir?
2. Cleaning up the .toml and .gradle files in https://github.com/grails/grails-quartz/tree/4.0.x/gradle and moving the versions to gradle.properties?

**Comment by jamesfredley** [comment]
@amondel2 

Grails projects are currently split with and without buildSrc.  I personally like without because it is simpler and version management is not independent, but it is up to you.  For start.grails.org generated projects on 6.2.2 and 7.0.0 default to without buildSrc.

Most Grails projects do not use .toml.  For the ones that do, it is possible to use versions from grails-bom and remove most of the versions from .toml files.  It would also be OK to convert away from .toml, if you want to go this direction.  Toml is cool, but it takes more time to see what it is doing, IMO.  

A good example of removing most versions from .toml:  https://github.com/grails/grails-spring-security-core/pull/1034/files
Anything with a version in https://repo.grails.org/ui/repos/tree/PomView/libs-snapshots-local/org/grails/grails-bom/7.0.0-SNAPSHOT/grails-bom-7.0.0-20241213.003552-182.pom can have the version removed.
