### ISSUE TITLE
Feature request - Make config available for reading triggers

### ISSUE THREAD

**Issue by anshbansal** [grails-plugins/grails-quartz#33]
Currently when the jobs are started the config is not available. Due to this the triggers cannot be made a part of the config and needs to be either hard-coded or manually read from a config file.

It would be good if config is available when triggers are evaluated.

**Comment by davydotcom** [comment]
`grailsApplication` is now on TriggerConfBuilder delegate and referencable in 
```
triggers = {
  simple name:'TestJobTrigger', repeatInterval:grailsApplication.config?.myJob?.repeatInterval ?: 300000l, startDelay:0

}
```
