### ISSUE TITLE
[Groovy truth] plugin is ignoring config value

### ISSUE THREAD

**Issue by yancovski** [grails-plugins/grails-quartz#37]
groovy construction from QuartzGrailsPlugin.groovy "quartzProperties['org.quartz.autoStartup'] as boolean"  always evaluates to true.
As a result of this "wonderful" and "modern" groovy usage I can't start quartz scheduler manually: 
if (quartzProperties['org.quartz.autoStartup']) {
   autoStartup = quartzProperties['org.quartz.autoStartup'] as boolean // evaluates to true
}

**Comment by yancovski** [comment]
Possible workaround is implement org.springframework.beans.factory.config.BeanPostProcessor interface and override postProcessBeforeInitialization:

@Override
    Object postProcessBeforeInitialization(Object bean, String beanName) {
        if(beanName == 'quartzScheduler') {
            bean.autoStartup = Boolean.valueOf(Holders.config.quartz.autoStartup)
        }
        return bean
    }

**Comment by rvanderwerf** [comment]
I've noticed this as well along with other config values. I checked in a fix to master
