### ISSUE TITLE
After update from 2.0.0 to 2.0.1 jobs not started

### ISSUE THREAD

**Issue by AlexKovynev** [grails-plugins/grails-quartz#39]
grails clean did not help, no errors.

Can I give any information, or else all of this problem?

**Comment by AlexKovynev** [comment]
Apparently stopped working without parameters in the configuration.

**Comment by salex772** [comment]
The same is for 2.0.3 and 2.0.4. 2.0.1 works incorrectly.

**Comment by ppazos** [comment]
2.0.13 also doesn't start
