### ISSUE TITLE
2.0.3 and 2.0.4 versions do not work with grails 3.0.11

### ISSUE THREAD

**Issue by salex772** [grails-plugins/grails-quartz#46]
When I use 'compile 'org.grails.plugins:quartz:2.0.3' (or 2.0.4) there is no any log on console during app start whereas 2.0.2 logs that plugin is started. But however that may be no jobs are started with version > 2.0.2.

Logger settings are logger("org.quartz", DEBUG)

But however that may be I cannot configure 2.0.2 also. It logs that it started but I see this:

Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

What does it meant 'NOT STARTED'? 

 Also I noticed that some jobs were started, some were not. Which started  they run at incorrect time or not run at all, although everything was made according to docs. I added QuartzGrailsPlugin.groovy file, added to application.groovy and application.yml

quartz {
	autoStartup = true
	//exposeSchedulerInRepository=true
}

but all these seems to be wrong.

**Comment by salex772** [comment]
Even worse - on 2.0.2 the shedule is taken from one job, whereas performing another.... )))

**Comment by AlexKovynev** [comment]
salex772: Hooray, I'm not crazy!!

**Comment by salex772** [comment]
I cannot make it work at all.

**Comment by adibak20** [comment]
Hello 

I tired install quartz plugin in grails 3.0.9 and I update plugin I had error: 

```
Warning:<i><b>root project 'project': Web Facets/Artifacts will not be configured properly</b>
Details: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':runtime'.
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find quartz.zip (org.grails.plugins:quartz:2.0.0).
Searched in the following locations:
    https://repo.grails.org/grails/core/org/grails/plugins/quartz/2.0.0/quartz-2.0.0.zip</i>

```

Can you tell me where am I doing wrong?
Help me...

**Comment by salex772** [comment]
Did you run "gradle lean" before it?

**Comment by adibak20** [comment]
Yes, nothing helps

**Comment by salex772** [comment]
What is in your "build.gradle"? Try to use 2.0.4
```
repositories {
	mavenLocal()
	maven {
		url = "http://dl.bintray.com/grails/plugins"
	}
	maven {
		url = "http://jcenter.bintray.com"
	}
	maven {
		url = "https://repo.grails.org/grails/core"
	}

	mavenCentral()
	jcenter()

}

 dependencies {
          compile 'org.grails.plugins:quartz:2.0.4'
    }


```

**Comment by salex772** [comment]
@AlexKovynev Alex, if you are familiar with that issue and as I see you are contributing to this plugin why it is not tested enough and nowhere is it specified as broken?

or I do smth wrong?

**Comment by rvanderwerf** [comment]
I'm not seeing these errors, can someone post a small example app to
demonstrate the issue?

**Comment by adibak20** [comment]
@salex772 Next is the same, I do not know what but grails looking for in the repo zip file and did not see him there.

In you, does it work?

**Comment by salex772** [comment]
My problem that plugin itself does not work as expected - only one job can fire. Other jobs sheduler doesn't see and also mess them in shedule. But I installed it without any problems. Any versions I have tried were installed wothout any trouble.

Please install new fresh grails application and then add example I posted above to your build.config. I'm sure that it is problem with your gradle or some libs or IDE.

**Comment by salex772** [comment]
@rvanderwerf this is a simple default project with three jobs. Nothing happens! (jobs must print and log)
1. grails create-app cronTest
2. copy files over default project

[cronTest.tar.gz](https://github.com/grails-plugins/grails-quartz/files/86420/cronTest.tar.gz)

**Comment by AlexKovynev** [comment]
1. I am not a contributor.
2. In your test you have identically "cron name". That's why the first task is performed only.
3. 2.0.4 is broken, pluginEnabled is disabled by default, if i set is to true i catch exception in

if (grailsApplication?.config?.quartz?.purgeQuartzTablesOnStartup?.toBoolean()==true) {

Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: static org.grails.config.NavigableMap.toBoolean() is applicable for argument types: () values: []
Possible solutions: asBoolean(), asBoolean(), toSorted()

**Comment by salex772** [comment]
What you mean by identically "cron name"? I thought this is the name of sheduling type, like "simple".
I get the error too if set pluginEnabled option. But on my real app with 2.0.4 this works as I described above - only one job task is sheduled though pluginEnabled is false by default.

**Comment by AlexKovynev** [comment]
static triggers = {
        cron name: 'cronTrigger', startDelay: 5000, cronExpression: '10 * * * * ?'
    }
cronTrigger is the name in all three jobs, if you set something different you get to work all three,

but it works on 2.0.1. In 2.0.4 are waiting for a response from a rvanderwerf  I hope.

**Comment by salex772** [comment]
Hmm, I really supposed that is not just a name but a trigger type and it should be set to 'cronTrigger', Perhaps some update to docs is needed.  Спасибо.

**Comment by rvanderwerf** [comment]
Exception in thread "main" groovy.lang.MissingMethodException is something
I'm going to try and get fixed tonight, if not tomorrow, someone else
reported this as well. Alexender I'll check out your project example thanks
for sending that in.

**Comment by rvanderwerf** [comment]
ok fixed the config values. As you guys were saying the default values turned the plugin off (my bad). Updated the readme as well to tell you to use unique trigger names. You can't have duplicate names triggers. I took your example @salex772 once I fixed the config issues (you can work around by setting the new config values in the config) and renamed the trigger and all 3 ran. So give 2.0.5 a spin I tested it in several apps without issues tonight.

**Comment by adibak20** [comment]
Hello, 
@salex772  was right. I built a new project and it runs very well.
I can not figure what I'm doing wrong in my project.

My build.gradle:
```
buildscript {
    ext {
        grailsVersion = project.grailsVersion
    }
    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        classpath 'com.bertramlabs.plugins:asset-pipeline-gradle:2.5.0'
        classpath "org.grails.plugins:hibernate4:4.3.5.4"
    }
}

plugins {
    id "io.spring.dependency-management" version "0.5.2.RELEASE"
    id 'org.hidetake.ssh' version '1.1.4'
}

version "0.1"
group "project"

apply plugin: "spring-boot"
apply plugin: "war"
apply plugin: "asset-pipeline"
apply plugin: 'idea'
apply plugin: "org.grails.grails-web"
apply plugin: "org.grails.grails-gsp"

ext {
    grailsVersion = project.grailsVersion
    gradleWrapperVersion = project.gradleWrapperVersion
}

assets {
    minifyJs = true
    minifyCss = true
}

repositories {
    mavenLocal()
    maven {
        url = "http://dl.bintray.com/grails/plugins"
    }
    maven {
        url = "http://jcenter.bintray.com"
    }
    maven {
        url = "https://repo.grails.org/grails/core"
    }

    mavenCentral()
    jcenter()

}

dependencyManagement {
    imports {
        mavenBom "org.grails:grails-bom:$grailsVersion"
    }
    applyMavenExclusions false
}

dependencies {
    compile "org.springframework.boot:spring-boot-starter-logging"
    compile "org.springframework.boot:spring-boot-starter-actuator"
    compile "org.springframework.boot:spring-boot-autoconfigure"
    provided  "org.springframework.boot:spring-boot-starter-tomcat"
    compile "org.grails:grails-dependencies"
    compile "org.grails:grails-web-boot"


    compile "org.grails.plugins:hibernate"
    compile "org.grails.plugins:cache"
    compile "org.hibernate:hibernate-ehcache"
    compile "org.grails.plugins:scaffolding"

    compile "org.jadira.usertype:usertype.jodatime:2.0"
    compile 'joda-time:joda-time:2.9.1'

    compile 'org.grails.plugins:spring-security-core:3.0.1'
    compile 'org.springframework.security:spring-security-core:3.2.9.RELEASE'
    compile 'org.springframework.security:spring-security-web:3.2.9.RELEASE'

    compile 'org.grails:grails-datastore-rest-client:5.0.0.RC2'

    compile 'org.flywaydb:flyway-core:3.0'

    compile 'org.grails.plugins:asynchronous-mail:1.2'
    compile "javax.mail:mail:1.4.1"

    runtime 'org.postgresql:postgresql:9.4-1200-jdbc41'
    runtime "org.grails.plugins:asset-pipeline"
    runtime 'org.grails.plugins:database-migration:2.0.0.RC1'

    testCompile "org.grails:grails-plugin-testing"
    testCompile "org.grails.plugins:geb"
    testRuntime 'org.seleniumhq.selenium:selenium-htmlunit-driver:2.44.0'

    console "org.grails:grails-console"

    compile 'org.grails.plugins:quartz:2.0.4'

}
```

And I had error: 

```
Warning:<i><b>root project 'up2you': Web Facets/Artifacts will not be configured properly</b>
Details: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':runtime'.
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find quartz.zip (org.grails.plugins:quartz:2.0.4).
Searched in the following locations:
    http://dl.bintray.com/grails/plugins/org/grails/plugins/quartz/2.0.4/quartz-2.0.4.zip</i>
Warning:<i><b>root project 'up2you': Web Facets/Artifacts will not be configured properly</b>
Details: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':runtime'.
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find quartz.zip (org.grails.plugins:quartz:2.0.4).
Searched in the following locations:
    http://dl.bintray.com/grails/plugins/org/grails/plugins/quartz/2.0.4/quartz-2.0.4.zip</i>
```

Do you know someone depending on what's going on here?

**Comment by adibak20** [comment]
Its working now. The problem turned out to be in temporary files. I deleted a folder .m2 from home and downloaded the have a new everything.

**Comment by salex772** [comment]
Yep, It's obvious.
