### ISSUE TITLE
Jobs not starting with grails 3.0.4 and quartz 2.0.1

### ISSUE THREAD

**Issue by timo-klarshift** [grails-plugins/grails-quartz#48]
Adding 'org.grails.plugins:quartz:2.0.1' as dependency to my grails 3.0.4 project will not run any job at all.

After changing to 'org.grails.plugins:quartz:2.0.5' it works as expected. Maybe the part of build.gradle should be updated for the latest branch accordingly.

**Comment by magx2** [comment]
The same in my app!

**Comment by rvanderwerf** [comment]
2.0.6 released today. Older versions may have issues.

**Comment by ppazos** [comment]
jobs are not starting in grails 3.3.10 with quartz 2.0.13
