### ISSUE TITLE
Add support of "L" modifier

### ISSUE THREAD

**Issue by salex772** [grails-plugins/grails-quartz#49]
for tasks for last day of the month

**Comment by salex772** [comment]
Hey guys, February is coming, only 28 days. My jobs must be performed on the month's last day. Any ideas why it is not working?

**Comment by erichelgeson** [comment]
Can you provide some details on what is not working? looks fine to me:

```
cron name:'someTriggerName', startDelay:10000, cronExpression: "0 15 10 L * ?"
```

```
trigger.nextFireTime == Sun Jan 31 10:15:00 UTC 2016
```

**Comment by salex772** [comment]
Not working if specify smth like '0 0 2 15,L * ?' . My task must run on 15th and on the last day of the month, that causes the error " Cron expression '0 0 2 15,L * ?' in the job class com.domainboost.RedistributeJob is not a valid cron expression"

**Comment by erichelgeson** [comment]
That is just an invalid quartz cron expression. You can not mix int and L.

A simple workaround is to create 2 cron triggers in your job with correct quartz cron syntax: 
```groovy
triggers {
    cron name:'midMonthTrigger',   cronExpression: "0 0 2 15 * ?"
    cron name:'endOfMonthTrigger', cronExpression: "0 0 2 L * ?"
}
```

You can validate its invalid by just using quartz `CronTrigger` builder without the plugin and getting the same error, also this site is useful http://www.cronmaker.com/

**Comment by salex772** [comment]
Ok, thanks, I already created two jobs. BTW, how to debug quartz in integration test?

**Comment by kefirfromperm** [comment]
Not a bug.
