### ISSUE TITLE
2.0.5 not working without jdbcStore (session not found errors)!!

### ISSUE THREAD

**Issue by AlexKovynev** [grails-plugins/grails-quartz#50]
// The session listener if is needed
                if (hasHibernate && jobClass.sessionRequired && hasJdbcStore) {
                    SessionBinderJobListener listener = ctx.getBean(SessionBinderJobListener.NAME)
                   
....

**Comment by zyro23** [comment]
`SessionBinderJobListener` registration should not depend on the type of jobstore quartz is using

**Comment by rvanderwerf** [comment]
this has been release in 2.0.6 today thanks
