### ISSUE TITLE
2.0.5 did not start due to missed tables

### ISSUE THREAD

**Issue by sphinks** [grails-plugins/grails-quartz#55]
I try to use 2.0.5 and if fails by default:

org.springframework.context.ApplicationContextException: Failed to start bean 'quartzScheduler'; nested exception is org.springframework.scheduling.SchedulingException: Could not start Quartz Scheduler; nested exception is org.quartz.SchedulerConfigException: Failure occured during job recovery. [See nested exception: org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: Table 'localShema.QRTZ_LOCKS' doesn't exist [See nested exception: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'localShema.QRTZ_LOCKS' doesn't exist]

It needs some database layout, but did not create it by itself, also I can not find any sql script to create all needed db stuff.

**Comment by AlexKovynev** [comment]
This is double of https://github.com/grails-plugins/grails-quartz/issues/50. I am already propose the pull request, I am don't undestend why owner does not apply it. I think your debug problem linked with this, maybe you better play with 2.0.1, as i see by commits between them is not a big difference.

**Comment by sphinks** [comment]
Alex, thanks. But do you have sql script for creating all need db layout? I want to launch 2.0.5 anyway, so need to create layout manually.

**Comment by AlexKovynev** [comment]
https://quartz-scheduler.org/downloads, Docs\DBTables in archive

**Comment by tolyo** [comment]
+1 on this issue

**Comment by rvanderwerf** [comment]
we can't auto create the tables, the proper schema needs to be applied for
the ddl for your database from the quartz distribution. If you don't have a
database set the jdbcstore to false in the config and it will use the ram
store.

**Comment by AlexKovynev** [comment]
Please publish the version 2.0.6 , my patch already in it. Otherwise ramstore is not working with hibernate.

**Comment by rvanderwerf** [comment]
2.0.6 has published from bug #50  - however the plugin will not create tables for you, as I said you have to use the DDL supplied with quartz distro for your particular database.
