### ISSUE TITLE
Grails 3.1.0.RC1 is not picking up grails-app/config/quartz.properties

### ISSUE THREAD

**Issue by memorydoor** [grails-plugins/grails-quartz#57]
Hi There,

I'm using     compile "org.grails.plugins:quartz:2.0.0" in build.gradle
Trying to changes the default threadCount from 10 to 20.

Having quartz.properties with following settings placed under grails-app/config.
org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount=20

Unfortunately the application logs still saying 10 threads.

2016-02-04 21:23:38 INFO org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.2.1) 'quartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

Does anyone had the same issue? Appreciate your help.

**Comment by madhacked** [comment]
In looking at the code it seems like the startup code is looking for a "quartz" block in your Grails config.

For example: 

```
quartz {
            dataSource.myDS.driver = "com.mysql.jdbc.Driver"
...
}
```

I was able to use this successfully in Grails 3.2.3. So it looks like you'll need to move the properties from the quartz.properties file over to your Grails configuraiton.

**Comment by davydotcom** [comment]
correct this information should be sent to grails config instead as startup behavior is a bit different in grails
