### ISSUE TITLE
2.0.1+ not registering jobs if autoStartup=false

### ISSUE THREAD

**Issue by zyro23** [grails-plugins/grails-quartz#59]
autoStartup = false should just prevent the scheduler from starting but register and schedule jobs as it used to. currently no job is defined/scheduled at all if autoStartup=false
ref. https://github.com/grails-plugins/grails-quartz/blob/master/src/main/groovy/quartz/QuartzGrailsPlugin.groovy#L285

**Comment by hbogaards** [comment]
I moved a Job to a different package and then the Job was not correctly configured, so I think that my fix is not fully correct.

I think that the check on `autoStartup` should be completely removed
