### ISSUE TITLE
Jobs fire while app is booting do not have a hibernate session

### ISSUE THREAD

**Issue by erichelgeson** [grails-plugins/grails-quartz#62]
Grails 3.1.1 Quartz Plugin 2.0.1-2.0.7

When a job is scheduled instantly (eg resuming from a persistent store) It will fail without a Hibernate Session. Subsequent runs do have a Hibernate session -

```
ERROR grails.plugins.quartz.listeners.ExceptionPrinterJobListener - Exception occurred in job: Grails Job org.quartz.JobExecutionException: org.hibernate.HibernateException: No Session found for current thread
```

We tried to set the `loadAfter`, but it did not resolve the issue. https://github.com/grails-plugins/grails-quartz/commit/0e2a909936afeab9322035e1a5da84ef3700ebfd

```
DEBUG quartz.QuartzGrailsPlugin - Registering hibernate SessionBinderJobListener
INFO org.grails.plugins.datasource.TomcatJDBCPoolMBeanExporter - Registering beans for JMX exposure on startup
ERROR grails.plugins.quartz.listeners.ExceptionPrinterJobListener - Exception occurred in job: Grails Job
```

^ exception before the app starts

```
Grails application running at http://localhost:8080 in environment: development
DEBUG grails.plugins.quartz.listeners.SessionBinderJobListener - Persistence session is flushed.
DEBUG grails.plugins.quartz.listeners.SessionBinderJobListener - Persistence session is opened.
```

^ `SessionBinderJobListener` working as expected after app is running

I don't see this behavior in Grails 2.5.3 with Quartz Plugin 1.0.2

**Comment by davydotcom** [comment]
resolved in 2.0.10
