### ISSUE TITLE
RAMJobStore not loading at startup

### ISSUE THREAD

**Issue by coaxcable** [grails-plugins/grails-quartz#64]
The error indicates that the RAMJobStore tables are not created at startup.  I'm using Grails 3.1.1.  I tried plugin version 2.0.5 - 2.0.8 with the same failure.  Plugin version 2.0.4 is working.  Appreciate your help with this.

ERROR org.springframework.boot.SpringApplication - Application startup failed
org.springframework.context.ApplicationContextException: Failed to start bean 'quartzScheduler'; nested exception is org.springframework.scheduling.SchedulingException: Could not start Quartz Scheduler; nested exception is org.quartz.SchedulerConfigException: Failure occured during job recovery. [See nested exception: org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: Table "QRTZ_LOCKS" not found; SQL statement:
SELECT \* FROM QRTZ_LOCKS WHERE SCHED_NAME = 'quartzScheduler' AND LOCK_NAME = ? FOR UPDATE [42102-190] [See nested exception: org.h2.jdbc.JdbcSQLException: Table "QRTZ_LOCKS" not found; SQL statement:
SELECT \* FROM QRTZ_LOCKS WHERE SCHED_NAME = 'quartzScheduler' AND LOCK_NAME = ? FOR UPDATE [42102-190]]]

**Comment by arjangch** [comment]
The same issue confirmed.

**Comment by AlexKovynev** [comment]
I don't understand, RAMJobStore tables? It's look like you enable JDBCStore, for JDBCStore you need to create tables by self.

**Comment by PatrickHuetter** [comment]
I can also confirm this issue. 
My configuration:
```
quartz:
    jdbcStore: false
    autoStartup: true
```
