### ISSUE TITLE
1.0.2 Exception loading Grails 2.5.3 while using Cron trigger

### ISSUE THREAD

**Issue by KerchumA222** [grails-plugins/grails-quartz#66]
Snippet of the Job

    def concurrent = false
    def description = "Does stuff."
    static triggers = {
        cron name: 'cronTrigger', startDelay: 10000, cronExpression: "0 0 8 * * * *" //8AM Every day
    }

    void execute() {}

Exception thrown:

    Error loading plugin manager: Unable to locate constructor with Class parameter for class grails.plugins.quartz.DefaultGrailsJobClass (Use --stacktrace to see the full trace)

The exception is not thrown when using a simple trigger.

**Comment by erichelgeson** [comment]
That is not a valid `cronTrigger`  (if it was it would 

You can validate here http://www.cronmaker.com/

Reading your code comment you might want something like: `0 0 8 * * ? *`

**Comment by KerchumA222** [comment]
That was the issue. Thank you for the fast response. I was just about to report back that I figured this out from enabled the `--stacktrace` option. It would be nice if exception that's thrown was more descriptive though.
