### ISSUE TITLE
2.0.8 -Grails 3.1.4 Session re-used on thread

### ISSUE THREAD

**Issue by mphouston** [grails-plugins/grails-quartz#67]
After the upgrade from Grails 3.0.11 to 3.1.4 on my plugin, I noticed that the hibernate session is not reset on the Quartz worker thread when the thread is re-used.  This resulted in a lot of exceptions:  'org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction' after the 11th run. 

The thread pool used threads 1-10 fine, but when the job ran a 11th time, we hit the exception.  The thread was still bound to the original hibernate session that had stale data.  The domain object's version was the same as it was when the thread was first used.

As a temporary work around, I added this at the end of the job:

    grailsApplication?.mainContext?.sessionFactory?.currentSession?.clear()

This probably is not a huge problem if I have to leave it in the Job, but it would be great if the plugin cleared the session.  Also, I am using the RAM store.  I assume the JDBC Store might behave differently.  My only configuration option in application.yml for this plugin is:

    quartz.jdbcStore: false

(I suspect something in thread handling changed in Grails 3.1.x, but I could not find an obvious issue).

**Comment by AlexKovynev** [comment]
I propose changes, waiting for new version with it, before this most stable is 2.0.1 i think

**Comment by rvanderwerf** [comment]
Thanks for your contribution! I will test it with the jdbc turned on to see if there are no ill effects on it before releasing.

**Comment by AlexKovynev** [comment]
As you can see in the code with jdbcStore is running, but it is a problem, it works only with jdbcStore. We all look forward to the new version 2.0.9!

**Comment by rvanderwerf** [comment]
2.0.9 is released! Thanks again for your contribution.
