### ISSUE TITLE
Plugin does not run

### ISSUE THREAD

**Issue by arjangch** [grails-plugins/grails-quartz#68]
I created a brand new grails app and tried this plugin. But it doesnot run at all. 

- compile 'org.grails.plugins:quartz:2.0.4'
- compile 'org.grails.plugins:quartz-monitor:1.2'
- | Grails Version: 3.1.1
- | Groovy Version: 2.4.5
- | JVM Version: 1.8.0_73

`
static triggers = {
        simple repeatInterval: 1000
}
`
`
void execute() {
        println "Job run!"
    }
}
`

**Comment by brettcrowell** [comment]
I'm having the same issue, the only workaround I can provide is switching to a different version...

```
compile 'org.grails.plugins:quartz:2.0.0.M4'
```

This post helped reach that conclusion...
https://stackoverflow.com/questions/6259066/how-to-run-every-25-seconds-in-quartz-scheduler

**Comment by arjangch** [comment]
Found the solution to my issue.  Don't store it in DB. 
If you want to store it in DB you need to create tables by yourself. 

Add this in application.yml
```
quartz:
    autoStartup: true
    jdbcStore: false
```
