### ISSUE TITLE
NPE when attempting to schedule or trigger a job

### ISSUE THREAD

**Issue by dfarm3r** [grails-plugins/grails-quartz#70]
Grails Version: 3.1.6
Groovy Version: 2.4.6
JVM Version: 1.8.0_91
Plugin version: 2.0.1

Description: When setting up a simple job an NPE is thrown because the internalJobArtefact.group is null. The underlying issue looks to be a missing property exception.

Steps to reproduce: 

Set up a simple job:

class MyJob {
    def group = "Reporting Group"
    def description = "Simple Description"

```
def execute(context) {
    println context.mergedJobDataMap.foo
}
```

}

From a controller call the triggerNow method (or any way of scheduling a job)
        MyJob.triggerNow([foo: "it just works"])

Results in the NPE being thrown and the job not being executed.

**Comment by dfarm3r** [comment]
has anyone been able to reproduce this behavior?

**Comment by dfarm3r** [comment]
FYI...I just realized the documentation is not correct. This issue is caused by the default configuration of the plugin. The documentation states that the default, for autoStartup is 'true'. This was not the case, I had to explicitly configure this to be true in application.yml which then allowed things to run smoothly.

**Comment by OsaSoft** [comment]
This. Thank you! I Had the same issue and couldnt figure out what was wrong, googling didnt help at all. Decided to look into issues in the plugin as a last hope. Setting autoStartup to true in application.yml fixed this for me

**Comment by rvanderwerf** [comment]
Apologies last or reversed the default as people didn't like it will update the docs!

**Comment by YouriAckx** [comment]
Setting `autoStartup` to `true` causes the job to be triggered when the application starts up. Not the intended behavior either...

**Comment by hamza3202** [comment]
Is this fixed?

**Comment by davydotcom** [comment]
this should be resolved now
