### ISSUE TITLE
Quartz autoStartup too early

### ISSUE THREAD

**Issue by davydotcom** [grails-plugins/grails-quartz#71]
Jobs are starting before application is fully running. This tends to cause the application startup time to take longer than necessary and also can cause jobs to access code not fully ready for access. It may be advisable to move the autoStartup features of the Quartz plugin to a Bootstrap class instead of in the Plugin class events.

**Comment by davidklebanoff** [comment]
Not to diminish the issue, but you could use `startDelay` as a workaround, correct?

**Comment by davydotcom** [comment]
Not in JDBC clustered mode it assumed the delay has already been assessed

**Comment by rvanderwerf** [comment]
I can verify this happening to us as well but I don't have a good fix yet.

**Comment by yvesf** [comment]
This fix with using onStartup requires at least grails 3.1.6 because it depends on this other fix: https://github.com/grails/grails-core/issues/9883

**Comment by yvesf** [comment]
There is already a startupDelay implemented in `SchedulerFactoryBean`. One can configure it like this:
```groovy
class Application extends GrailsAutoConfiguration {
  ...
  @Override
  Closure doWithSpring() {
    return { ->
      final quartzSchedulerDef = getBeanDefinition('quartzScheduler') as GenericBeanDefinition
      quartzSchedulerDef.propertyValues.addPropertyValue('startupDelay', TimeUnit.MINUTES.toSeconds(7))
    }
  }
```

has anyone tried that? So far I didn't find a problem with doing it this way.
