### ISSUE TITLE
SessionBinderJobListener is only registered if autoStart=true

### ISSUE THREAD

**Issue by yvesf** [grails-plugins/grails-quartz#73]
In QuartzGrailsPlugin, only if `pluginEnabled` and `autoStart` is both true then `scheduleJob` is run. The problem is that `scheduleJob` not only schedules the job but also configures the SessionBinderJobListener.

In consequence, if you activate grails later after startup (there is a grails plugin for quartz that provides an UI for that) then the jobs won't have a Session when they are triggered.

**Comment by davydotcom** [comment]
resolved in 2.0.10
