### ISSUE TITLE
Not working in Grails 3.2.0

### ISSUE THREAD

**Issue by ismeleo** [grails-plugins/grails-quartz#78]
Followed the document to create the job but not working in Grails 3.2.0.

**Comment by rvanderwerf** [comment]
Can you post a sample app showing the problem?

**Comment by ismeleo** [comment]
Hello, I am sorry that I used an older version 2.0.3 which I think it may not compatible with the latest Grails version so that it was not working.

Now I used the latest 2.0.9 version and it is ok now. Thanks!
