### ISSUE TITLE
It seems the plugin does not understand application.groovy

### ISSUE THREAD

**Issue by kefirfromperm** [grails-plugins/grails-quartz#81]
I try to prevent start of the scheduler but it starts anyway.

application.groovy
```groovy
quartz.autoStartup = false
```

doesn't work.

**Comment by rvanderwerf** [comment]
hmm this is odd, we have this working in our app:
	development {
		quartz {
			autoStartup = false
			jdbcStore = true
			purgeQuartzTablesOnStartup = true
			pluginEnabled = true
			props(jdbcProps)
		}
	}
and it does not start

**Comment by jglapa** [comment]
I'm observing the same but funnily enough this behaved like that also with `Grails 2.x` and plugin `v1`

**Comment by davydotcom** [comment]
autoStartup behaves weird with the scheduler. this has been addressed I believe in 2.0.10
