### ISSUE TITLE
Release 2.0.13?

### ISSUE THREAD

**Issue by mamunsrdr** [grails-plugins/grails-quartz#95]
@graemerocher @jeffbrown @davydotcom requesting 2.0.13 version release as previous versions are incompatible with grails >= 3.3.0

**Comment by lploom** [comment]
Yes. Documentation says use 2.0.13 for Grails 3.3. However, it is not 2.0.13 is not released...

2.0.13 for Grails 3.3.*
Properties changed to static from def.
For example: def concurrent will be now static concurrent.

**Comment by mamunsrdr** [comment]
Actually I submitted #93 pull request to resolve #91 , but not released

**Comment by puneetbehl** [comment]
We have released `v2.0.13`
